import sys
import os
import unittest
import cv2
import torch

# Add parent directory to path
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

# Mock args for Wav2LipInference
class Args:
    def __init__(self):
        self.checkpoint_path = os.path.abspath(os.path.join(os.path.dirname(__file__), '../core/checkpoints/wav2lip_gan.pth'))
        self.face = ""
        self.audio = ""
        self.outfile = ""
        self.static = True
        self.fps = 25.
        self.pads = [0, 10, 0, 0]
        self.wav2lip_batch_size = 1 # Reduced for testing
        self.resize_factor = 1
        self.out_height = 480
        self.crop = [0, -1, 0, -1]
        self.box = [-1, -1, -1, -1]
        self.rotate = False
        self.nosmooth = False
        self.img_size = 96

# Add core to sys.path so imports in wav2lip_interface work
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '../core')))

from wav2lip_interface import Wav2LipHandler

class TestWav2Lip(unittest.TestCase):
    def test_gpu_availability(self):
        print(f"PyTorch Version: {torch.__version__}")
        print(f"CUDA Available: {torch.cuda.is_available()}")
        if torch.cuda.is_available():
            print(f"CUDA Device: {torch.cuda.get_device_name(0)}")
        else:
            print("WARNING: CUDA not available, running on CPU.")

    def test_inference(self):
        print("Testing Wav2Lip Inference...")
        
        # Paths
        checkpoint_path = os.path.abspath(os.path.join(os.path.dirname(__file__), '../core/checkpoints/wav2lip_gan.pth'))
        audio_path = os.path.abspath(os.path.join(os.path.dirname(__file__), 'output/test_audio.wav')) # Generated by TTS test
        image_path = os.path.abspath(os.path.join(os.path.dirname(__file__), '../static/images/einstein.jpg'))
        
        # Create dummy audio if TTS test wasn't run
        if not os.path.exists(audio_path):
            print("Generating dummy audio for test...")
            from tts_interface import OfflineTTS
            tts = OfflineTTS()
            os.makedirs("tests/output", exist_ok=True)
            audio_path = tts.generate_audio("Test audio.", "tests/output")
            # Rename to match expected
            os.rename(audio_path, os.path.join("tests/output", "test_audio.wav"))
            audio_path = os.path.join("tests/output", "test_audio.wav")

        self.assertTrue(os.path.exists(checkpoint_path), "Checkpoint not found")
        self.assertTrue(os.path.exists(audio_path), "Audio file not found")
        self.assertTrue(os.path.exists(image_path), "Avatar image not found")

        handler = Wav2LipHandler(checkpoint_path)
        
        # Check if it picked up the GPU
        print(f"Inference Device: {handler.inference.device}")
        
        # Run inference
        print("Running processing loop...")
        frame_count = 0
        for frame in handler.process(audio_path, image_path):
            frame_count += 1
            if frame_count >= 5: # Just check first few frames
                break
        
        print(f"Generated {frame_count} frames.")
        self.assertTrue(frame_count > 0, "No frames generated")
        print("Wav2Lip Test Passed!")

if __name__ == '__main__':
    unittest.main()
